### PR TITLE
Implemented sorting discussion posts by post time and vote

### LINKED ISSUE #24: Order Discussion Posts by Vote
Allow students to sort the posts using a drop-down menu.

Available sorting options: 
Posts newest -> oldest (default)
Posts oldest -> newest
Votes highest -> lowest
Votes lowest -> highest

### PR DESCRIPTION
**Pull request by hirokiterashima**
Test that the sort menu appears at the top right of the discussion forum and allows users to sort posts by the following options:
- Posts newest -> oldest (default)
- Posts oldest -> newest
- Votes highest -> lowest
- Votes lowest -> highest

Resolves #24

### CODE REVIEW

**Comment by JoelWiebe** [comment]
As we discussed, let's try re-sorting for each time a new post or vote is added.

**Review by JoelWiebe — CHANGES_REQUESTED** [review]
Can we resort each time a new post is added or vote is made?

**Review by JoelWiebe — CHANGES_REQUESTED** [review]
Tested resorting with 2 users for both voting and new posts--works well.

Only change needed is in the sort by list, fix the typo for "Most Popular -> Least Popular"

**Comment by hirokiterashima** [comment]
Fixed typo. Thanks for catching.

**Review by JoelWiebe — APPROVED** [review]
Looks/works great!

**Pull request merged**
