### PR TITLE
issue 18 only show active tasks

### LINKED ISSUE #18: Filter tasks in TA Tools Overview to only show active tasks
Rather than listing all steps for students, by default, only show steps which have tasks for teachers to respond to (i.e. student request for approval).

### PR DESCRIPTION
**Pull request by aperritano**

### CODE REVIEW

**Review by JoelWiebe — CHANGES_REQUESTED** [review]
The table appears to successfully show only the tasks labelled as "active" but there appears to be an issue with how tasks are being labelled as active.

Testing with one student in a project with three steps.
1. Navigating to step 1, the task for step 1 is marked as active
2. Navigating to step 2, both the task for step 1 and step 2 are marked as active
3. Navigating to step 3, the task for step 1 is still marked as active
So, the task for step 1 stays stuck and only the task for step 2 appropriately toggled on and off.

Testing with another student account. Step 1 never showed up, step 2 worked, and step 3 was never shown.

What are the conditions for "active" to show and hide? Might there be a reason why some are never labelled as "active" and others stay stuck on "active"?

**Comment by aperritano** [comment]
What is an 'active' step? For example, if a step is uncompleted and the student moves on, is that still 'active'?

**Comment by JoelWiebe** [comment]
Good question. Initially I was thinking that the active step should be whatever step a student is viewing. But now I'm rethinking it. For this interface we probably don't care about what students are viewing but rather steps with pending requests (i.e. request for help or request for approval). All others aren't really relevant to TAs at this point.

**Comment by JoelWiebe** [comment]
Can we have the default view only show steps with active requests/tasks for TAs to complete?

**Pull request closed without merging**
